### ISSUE TITLE
可否添加上 SHA1/MD5 校验信息

### ISSUE THREAD

**Issue by sxzz** [SukkaW/qqwry-mirror#2]
Thanks.

P.S. CDN 其实可以推荐使用 jsDelivr，更快一些
[https://cdn.jsdelivr.net/gh/SukkaW/qqwry-mirror@gh-pages/QQWry.Dat](https://cdn.jsdelivr.net/gh/SukkaW/qqwry-mirror@gh-pages/QQWry.Dat)

**Comment by SukkaW** [comment]
@sxzz 上游纯真并没有提供 SHA1/MD5 信息。

**Comment by sxzz** [comment]
或许可以在sync.sh中生成一下

**Comment by SukkaW** [comment]
使用 jsDelivr 分发二进制文件是完全不合理的。我已经向 jsDelivr 申请 Block 我的 Repo 以避免任何人通过 jsDelivr 进行下载 #18188

**Comment by sxzz** [comment]
got it
